### ISSUE TITLE
nolo se hermano, no me termina de convencer la wea

### ISSUE THREAD

**Issue by nnachonesa** [Michael-Liendo/michaelliendo.com#45]

**Comment by Michael-Liendo** [comment]
Hola, ¿a qué te refieres?

**Comment by nnachonesa** [comment]
mira, primero que dejas muchos espacios en blanco donde podrías aportar más información, imágenes etc

**Comment by Michael-Liendo** [comment]
okey, lo tendré en cuenta. muchas gracias 🔥
